# This file was generated by GoReleaser. DO NOT EDIT.
cask "sssh" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "4f150ad386e467a02647d60a273dc55b6cdd9bee791114ae50a7ca6a1de1f51b"
      url "https://github.com/dmnkx/homebrew-sssh/releases/download/v#{version}/sssh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e2a5577baa665a9f3a44546194b400117c05317567a5e6a50ed651c5e7c22eb"
      url "https://github.com/dmnkx/homebrew-sssh/releases/download/v#{version}/sssh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "72a5ed13f0de174a2033c352d12cdf6afd08f48b17b9f42e346de7ed59552a6e"
      url "https://github.com/dmnkx/homebrew-sssh/releases/download/v#{version}/sssh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "eecb59c756c9ab9cdbc8fda6b205cbbd9e2c6781b8b835981f0d1af9b548d541"
      url "https://github.com/dmnkx/homebrew-sssh/releases/download/v#{version}/sssh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sssh"
  desc "SSH into hosts using ~/.ssh/config aliases"
  homepage "https://github.com/dmnkx/homebrew-sssh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sssh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sssh"]
    end
  end

  # No zap stanza required
end
